gcc-7-release:
  tags:
    - artful
  script:
    - export CXX=g++-7
    - export CC=gcc-7
    - mkdir -p build-gcc-7-release
    - cd build-gcc-7-release
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - make -j12 lmdb-test
    - ./lmdb-test

clang-5-debug-asan:
  tags:
    - artful
  script:
    - export CXX=clang++
    - export CC=clang
    - export CXXFLAGS="-stdlib=libc++ -fsanitize=address -fno-omit-frame-pointer"
    - mkdir -p build-clang-5-debug-asan
    - cd build-clang-5-debug-asan
    - cmake -DCMAKE_BUILD_TYPE=Debug ..
    - make -j12 lmdb-test
    - ./lmdb-test

gcc-7-valgrind:
  tags:
    - artful
  script:
    - export CXX=g++-7
    - export CC=gcc-7
    - mkdir -p gcc-7-valgrind
    - cd gcc-7-valgrind
    - cmake -DCMAKE_BUILD_TYPE=Debug ..
    - make -j12 lmdb-test
    - ./lmdb-test